import type {
  ClinicalNote,
  ClinicalTask,
  Communication,
  DemoUser,
  IntakeItem,
  Observation,
  Patient,
  ProviderHealth,
  ProviderId,
  RoundAction,
  SourceMeta,
} from "./types.js";
import { nursingPatientIds, siteConfiguration } from "./site-config.js";

const allClinicalPatientIds = [
  ...nursingPatientIds,
  "p-mei",
  "p-jonas",
  "p-eva",
  "p-samir",
  "p-paul",
  "p-aline",
  "p-theo",
  "p-mila",
  "p-noah",
];
const activeWardId = siteConfiguration.department.id;
const qualificationsFor = (actorId: string): string[] =>
  siteConfiguration.actorQualifications[actorId] ?? [];
const assignedPatientsFor = (actorId: string): string[] =>
  siteConfiguration.staffAssignments.find(
    (assignment) => assignment.actorId === actorId,
  )?.patientIds ?? nursingPatientIds;

export const DEMO_NOW = "2026-09-05T08:00:00.000Z";

function source(
  provider: SourceMeta["provider"],
  externalId: string,
  version = 1,
  effectiveAt = DEMO_NOW,
): SourceMeta {
  return {
    provider,
    externalId,
    version,
    mappingVersion: "demo-r4-ch-core-6.0.0-v1",
    effectiveAt,
    recordedAt: effectiveAt,
    receivedAt: effectiveAt,
    syncedAt: effectiveAt,
  };
}

export const users: DemoUser[] = [
  {
    id: "u-assistant",
    displayName: "Lea Bernasconi",
    role: "care-assistant",
    wardIds: [activeWardId],
    patientIds: assignedPatientsFor("u-assistant"),
    managedDevice: true,
    defaultPurpose: "direct-care",
    qualificationIds: qualificationsFor("u-assistant"),
  },
  {
    id: "u-nurse",
    displayName: "Nora Frei",
    role: "registered-nurse",
    wardIds: [activeWardId],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
    qualificationIds: qualificationsFor("u-nurse"),
  },
  {
    id: "u-nurse-evening",
    displayName: "Samira Vogel",
    role: "registered-nurse",
    wardIds: [activeWardId],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
    qualificationIds: qualificationsFor("u-nurse-evening"),
  },
  {
    id: "u-physician",
    displayName: "Dr. David Keller",
    role: "physician",
    wardIds: [activeWardId, "ltc-1"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
    qualificationIds: qualificationsFor("u-physician"),
  },
  {
    id: "u-physician-evening",
    displayName: "Dr. Elif Aydin",
    role: "physician",
    wardIds: [activeWardId],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
    qualificationIds: qualificationsFor("u-physician-evening"),
  },
  {
    id: "u-pharmacy",
    displayName: "Giulia Rossi",
    role: "pharmacy",
    wardIds: [activeWardId],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-physio",
    displayName: "Marc Dubois",
    role: "physiotherapy",
    wardIds: [activeWardId],
    patientIds: nursingPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-ergo",
    displayName: "Sofia Meier",
    role: "occupational-therapy",
    wardIds: [activeWardId],
    patientIds: ["p-mei"],
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-transport",
    displayName: "Jonas Roth",
    role: "transport",
    wardIds: [activeWardId],
    patientIds: ["p-luca"],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-service",
    displayName: "Elena Huber",
    role: "service",
    wardIds: [activeWardId],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-admin",
    displayName: "Mia Schmid",
    role: "administration",
    wardIds: [activeWardId],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "administration",
  },
  {
    id: "u-manager",
    displayName: "Noah Graf",
    role: "management",
    wardIds: [activeWardId],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-hr",
    displayName: "Lina Wenger",
    role: "hr",
    wardIds: [],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-it",
    displayName: "Tim Gerber",
    role: "it",
    wardIds: [],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-quality",
    displayName: "Sara Baumann",
    role: "quality-safety",
    wardIds: [activeWardId],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "quality-review",
  },
];

export const patients: Patient[] = [
  {
    id: "p-anna",
    displayName: "Anna Beispiel",
    birthDate: "1941-03-18",
    mrn: "SH-260901-001",
    room: "214A",
    wardId: activeWardId,
    encounterId: "enc-anna-2026",
    allergyStatus: "confirmed",
    allergies: ["Penicillin – Exanthem"],
    risks: ["Sturzrisiko", "Antikoagulation"],
    diagnoses: [
      "Schenkelhalsfraktur links, postoperativ",
      "Arterielle Hypertonie",
    ],
    careGoals: [
      "Sicherer Transfer mit Rollator",
      "30 m Mobilisation bis 09.09.2026",
    ],
    medicationSummary: [
      "Torasemid: Diskrepanz 5 mg / 10 mg – keine Änderung in Pflegehelfer",
      "Apixaban 5 mg – nur lesbar",
    ],
    source: source("wicare", "WCD-L-10021", 7, "2026-09-05T06:45:00.000Z"),
  },
  {
    id: "p-luca",
    displayName: "Luca Demo",
    birthDate: "1937-11-02",
    mrn: "SH-260902-004",
    room: "207",
    wardId: activeWardId,
    encounterId: "enc-luca-2026",
    allergyStatus: "unknown",
    allergies: [],
    risks: ["Delirrisiko", "Hörminderung"],
    diagnoses: ["Dekonditionierung nach Pneumonie"],
    careGoals: ["Selbstständige Körperpflege am Lavabo"],
    medicationSummary: ["Medikationsabgleich durch Apotheke ausstehend"],
    source: source("carecoach", "CC-88004", 4, "2026-09-05T06:30:00.000Z"),
  },
  {
    id: "p-mei",
    displayName: "Mei Muster",
    birthDate: "1948-06-27",
    mrn: "SH-260903-002",
    room: "211",
    wardId: activeWardId,
    encounterId: "enc-mei-2026",
    allergyStatus: "confirmed",
    allergies: ["Latex"],
    risks: ["Aspirationsrisiko"],
    diagnoses: ["Zustand nach ischämischem Insult"],
    careGoals: ["Sicheres Schlucken gemäss Logopädieplan"],
    medicationSummary: ["Medikation im KIS – schreibgeschützt"],
    source: source("sap-vitals", "SAP-PAT-7731", 3, "2026-09-05T07:00:00.000Z"),
  },
  {
    id: "p-ruth",
    displayName: "Ruth Fiktiv",
    birthDate: "1939-05-12",
    mrn: "SH-260904-006",
    room: "205",
    wardId: activeWardId,
    encounterId: "enc-ruth-2026",
    allergyStatus: "unknown",
    allergies: [],
    risks: ["Sturzrisiko", "Schmerz bei Belastung"],
    diagnoses: ["Knie-Totalprothese rechts, postoperativ"],
    careGoals: ["Selbstständig ankleiden", "Sicher 20 m am Rollator"],
    medicationSummary: ["Medikation im führenden KIS – nur lesbar"],
    source: source("carecoach", "CC-88017", 2, "2026-09-05T06:35:00.000Z"),
  },
  {
    id: "p-peter",
    displayName: "Peter Beispiel",
    birthDate: "1943-09-21",
    mrn: "SH-260905-003",
    room: "208",
    wardId: activeWardId,
    encounterId: "enc-peter-2026",
    allergyStatus: "confirmed",
    allergies: ["Pflasterkleber"],
    risks: ["Flüssigkeitsretention", "Hautrisiko Unterschenkel"],
    diagnoses: ["Herzinsuffizienz, rehabilitative Stabilisierung"],
    careGoals: ["Gewicht täglich vergleichbar erfassen", "Ödeme beobachten"],
    medicationSummary: ["Diuretika-Verordnung im KIS – keine Änderung hier"],
    source: source("wicare", "WCD-L-10044", 5, "2026-09-05T06:42:00.000Z"),
  },
  {
    id: "p-sofia",
    displayName: "Sofia Muster",
    birthDate: "1951-01-30",
    mrn: "SH-260906-008",
    room: "216B",
    wardId: activeWardId,
    encounterId: "enc-sofia-2026",
    allergyStatus: "unknown",
    allergies: [],
    risks: ["Transfer mit zwei Mitarbeitenden", "Dekubitusrisiko"],
    diagnoses: ["Hemiparese links nach Insult"],
    careGoals: ["Sicherer Transfer in den Rollstuhl", "Haut bleibt intakt"],
    medicationSummary: ["Medikation im KIS – schreibgeschützt"],
    source: source("sap-vitals", "SAP-PAT-7810", 2, "2026-09-05T06:50:00.000Z"),
  },
  {
    id: "p-emil",
    displayName: "Emil Demo",
    birthDate: "1936-07-08",
    mrn: "SH-260907-005",
    room: "203",
    wardId: activeWardId,
    encounterId: "enc-emil-2026",
    allergyStatus: "explicit-negative",
    allergies: [],
    risks: ["Hörminderung", "Orientierung in neuer Umgebung"],
    diagnoses: ["Dekonditionierung nach abdominalem Eingriff"],
    careGoals: ["Hörhilfe selbst einsetzen", "Begleiteter Spaziergang"],
    medicationSummary: ["Medikationsabgleich abgeschlossen – nur lesbar"],
    source: source("carecoach", "CC-88029", 3, "2026-09-05T06:55:00.000Z"),
  },
  {
    id: "p-jonas",
    displayName: "Jonas Fiktiv",
    birthDate: "1960-02-14",
    mrn: "SH-260908-010",
    room: "202",
    wardId: activeWardId,
    encounterId: "enc-jonas-2026",
    allergyStatus: "confirmed",
    allergies: ["Metamizol – Urtikaria"],
    risks: ["Orthostase", "Sturzrisiko"],
    diagnoses: ["Polytrauma, rehabilitative Mobilisation"],
    careGoals: ["Treppentraining mit Physiotherapie", "Schmerzadaptierte ADL"],
    medicationSummary: ["Analgesieplan im KIS – nur lesbar"],
    source: source("wicare", "WCD-L-10058", 6, "2026-09-04T15:20:00.000Z"),
  },
  {
    id: "p-eva",
    displayName: "Eva Muster",
    birthDate: "1946-12-01",
    mrn: "SH-260909-011",
    room: "204",
    wardId: activeWardId,
    encounterId: "enc-eva-2026",
    allergyStatus: "explicit-negative",
    allergies: [],
    risks: ["Diabetes", "Hautintegrität"],
    diagnoses: ["Diabetisches Fusssyndrom, Nachsorge"],
    careGoals: ["Druckentlastung einhalten", "Hautveränderungen früh melden"],
    medicationSummary: ["Insulinplan im KIS – Pflegehelfer ändert keine Dosis"],
    source: source("carecoach", "CC-88035", 4, "2026-09-04T17:10:00.000Z"),
  },
  {
    id: "p-samir",
    displayName: "Samir Demo",
    birthDate: "1955-08-19",
    mrn: "SH-260910-012",
    room: "206",
    wardId: activeWardId,
    encounterId: "enc-samir-2026",
    allergyStatus: "unknown",
    allergies: [],
    risks: ["Aspirationsrisiko", "Kommunikation mit Dolmetschhilfe"],
    diagnoses: ["Dysphagie nach Insult"],
    careGoals: ["Sichere Kostform", "Bedürfnisse mit Bildtafel ausdrücken"],
    medicationSummary: ["Medikation in WiCare – schreibgeschützt"],
    source: source("wicare", "WCD-L-10061", 2, "2026-09-03T13:40:00.000Z"),
  },
  {
    id: "p-paul",
    displayName: "Paul Beispiel",
    birthDate: "1934-04-09",
    mrn: "SH-260911-013",
    room: "209",
    wardId: activeWardId,
    encounterId: "enc-paul-2026-b",
    allergyStatus: "confirmed",
    allergies: ["Kontrastmittel – frühere Reaktion unklar"],
    risks: ["Delirrisiko", "Wiederaufnahme nach Sturz"],
    diagnoses: ["Beckenprellung nach Sturz", "Leichte kognitive Störung"],
    careGoals: ["Tag-Nacht-Rhythmus stabilisieren", "Sicherer Toilettengang"],
    medicationSummary: ["Wiederaufnahmemedikation in Abklärung"],
    source: source("carecoach", "CC-88041", 8, "2026-09-05T05:50:00.000Z"),
  },
  {
    id: "p-aline",
    displayName: "Aline Fiktiv",
    birthDate: "1972-10-23",
    mrn: "SH-260912-014",
    room: "210",
    wardId: activeWardId,
    encounterId: "enc-aline-2026",
    allergyStatus: "explicit-negative",
    allergies: [],
    risks: ["Fatigue", "Belastungsintoleranz"],
    diagnoses: ["Long-COVID-Rehabilitation"],
    careGoals: ["Aktivitäten dosieren", "Pausen selbstständig planen"],
    medicationSummary: ["Keine pflegerelevante Medikationsänderung"],
    source: source("sap-vitals", "SAP-PAT-7892", 3, "2026-09-02T10:15:00.000Z"),
  },
  {
    id: "p-theo",
    displayName: "Theo Muster",
    birthDate: "1940-01-17",
    mrn: "SH-260913-015",
    room: "212",
    wardId: activeWardId,
    encounterId: "enc-theo-2026",
    allergyStatus: "unknown",
    allergies: [],
    risks: ["Weglauftendenz", "Hörminderung"],
    diagnoses: ["Vaskuläre Demenz, rehabilitative Abklärung"],
    careGoals: ["Orientierungshilfen nutzen", "Begleitete Wege"],
    medicationSummary: ["Medikation im führenden KIS – nur lesbar"],
    source: source("wicare", "WCD-L-10070", 5, "2026-09-01T08:30:00.000Z"),
  },
  {
    id: "p-mila",
    displayName: "Mila Demo",
    birthDate: "1981-07-11",
    mrn: "SH-260914-016",
    room: "215",
    wardId: activeWardId,
    encounterId: "enc-mila-2026",
    allergyStatus: "confirmed",
    allergies: ["Latex"],
    risks: ["Rollstuhltransfer", "Druckstelle Sitzbein"],
    diagnoses: ["Querschnittlähmung, Hilfsmittelanpassung"],
    careGoals: ["Selbstständiger Transfer", "Druckentlastung dokumentieren"],
    medicationSummary: ["Medikation im KIS – schreibgeschützt"],
    source: source("carecoach", "CC-88052", 7, "2026-08-31T14:00:00.000Z"),
  },
  {
    id: "p-noah",
    displayName: "Noah Fiktiv",
    birthDate: "1967-03-05",
    mrn: "SH-260915-017",
    room: "218",
    wardId: activeWardId,
    encounterId: "enc-noah-2026",
    allergyStatus: "explicit-negative",
    allergies: [],
    risks: ["Krampfanfall", "Belastungsangst"],
    diagnoses: ["Zustand nach neurochirurgischem Eingriff"],
    careGoals: ["Sicherer Stationsweg", "Belastung schrittweise steigern"],
    medicationSummary: ["Antikonvulsiva im KIS – keine Änderung hier"],
    source: source("sap-vitals", "SAP-PAT-7904", 4, "2026-08-30T16:45:00.000Z"),
  },
];

export const tasks: ClinicalTask[] = [
  {
    id: "t-bp-anna",
    patientId: "p-anna",
    encounterId: "enc-anna-2026",
    title: "Blutdruck kontrollieren",
    reason: "Erhöhter Morgenwert 168/96 mmHg",
    requesterId: "u-nurse",
    ownerRole: "care-assistant",
    ownerId: null,
    priority: "elevated",
    dueAt: "2026-09-05T08:45:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: [],
    completionEvidence: null,
    escalation: "Nach 30 Minuten an Pflegefachperson",
    source: source("pflegehelfer", "Task/t-bp-anna"),
  },
  {
    id: "t-mobilise-luca",
    patientId: "p-luca",
    encounterId: "enc-luca-2026",
    title: "Mobilisation mit Rollator",
    reason: "Rehabilitationsziel",
    requesterId: "u-physio",
    ownerRole: "care-assistant",
    ownerId: "u-assistant",
    priority: "routine",
    dueAt: "2026-09-05T10:30:00.000Z",
    state: "accepted",
    acknowledgementRequired: false,
    acknowledgedAt: "2026-09-05T07:42:00.000Z",
    dependencies: [],
    comments: ["Bei Schwindel pausieren und Pflegefachperson informieren."],
    completionEvidence: null,
    escalation: "Bei Nichtdurchführung Grund dokumentieren",
    source: source("pflegehelfer", "Task/t-mobilise-luca"),
  },
  {
    id: "t-transport-luca",
    patientId: "p-luca",
    encounterId: "enc-luca-2026",
    title: "Transport zur Radiologie",
    reason: "Kontrollaufnahme",
    requesterId: "u-physician",
    ownerRole: "transport",
    ownerId: null,
    priority: "routine",
    dueAt: "2026-09-05T11:20:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: [],
    completionEvidence: null,
    escalation: "Transportkoordination informieren",
    source: source("pflegehelfer", "Task/t-transport-luca"),
  },
  {
    id: "t-service-214",
    patientId: null,
    encounterId: null,
    title: "Defekte Leselampe Zimmer 214",
    reason: "Patientenkomfort",
    requesterId: "u-assistant",
    ownerRole: "service",
    ownerId: null,
    priority: "routine",
    dueAt: "2026-09-05T14:00:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: ["Kein klinischer Kontext erforderlich."],
    completionEvidence: null,
    escalation: "Facility-Leitung",
    source: source("pflegehelfer", "Task/t-service-214"),
  },
  {
    id: "t-intake-anna-med",
    patientId: "p-anna",
    encounterId: "enc-anna-2026",
    title: "Eintritt: Medikationsdiskrepanz klären",
    reason: "Import aus WiCare und Austrittsbericht ist widersprüchlich",
    requesterId: "system-import",
    ownerRole: "pharmacy",
    ownerId: null,
    priority: "elevated",
    dueAt: "2026-09-05T10:00:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: ["Keine Medikamentenänderung in Pflegehelfer."],
    completionEvidence: null,
    escalation: "Bei Unklarheit an ärztlichen Dienst und Pflegefachperson",
    source: source("pflegehelfer", "Task/t-intake-anna-med"),
  },
  {
    id: "t-intake-luca-consent",
    patientId: "p-luca",
    encounterId: "enc-luca-2026",
    title: "Eintritt: Einwilligungsdokument nachfordern",
    reason: "Import meldet fehlendes unterschriebenes Dokument",
    requesterId: "system-import",
    ownerRole: "administration",
    ownerId: null,
    priority: "routine",
    dueAt: "2026-09-05T14:00:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: [],
    completionEvidence: null,
    escalation: "Stationsadministration informieren",
    source: source("pflegehelfer", "Task/t-intake-luca-consent"),
  },
];

export const observations: Observation[] = [
  {
    id: "o-bp-anna-1",
    patientId: "p-anna",
    encounterId: "enc-anna-2026",
    code: "blood-pressure",
    label: "Blutdruck",
    value: 168,
    secondaryValue: 96,
    unit: "mmHg",
    effectiveAt: "2026-09-05T06:55:00.000Z",
    performerId: "device-bp-4",
    deviceId: "device-bp-4",
    status: "synced",
    version: 2,
    basedOnVersion: 1,
    approvalPolicy: "standard",
    approvals: ["device-gateway"],
    approvedAt: "2026-09-05T06:55:00.000Z",
    source: source(
      "device-gateway",
      "OBS-20260905-331",
      2,
      "2026-09-05T06:55:00.000Z",
    ),
  },
  {
    id: "o-temp-luca-1",
    patientId: "p-luca",
    encounterId: "enc-luca-2026",
    code: "temperature",
    label: "Temperatur",
    value: 37.4,
    secondaryValue: null,
    unit: "°C",
    effectiveAt: "2026-09-05T06:40:00.000Z",
    performerId: "u-nurse",
    deviceId: null,
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-05T06:40:00.000Z",
    source: source("carecoach", "CC-VITAL-411", 1, "2026-09-05T06:40:00.000Z"),
  },
  {
    id: "o-spo2-mei-1",
    patientId: "p-mei",
    encounterId: "enc-mei-2026",
    code: "oxygen-saturation",
    label: "Sauerstoffsättigung",
    value: 94,
    secondaryValue: null,
    unit: "%",
    effectiveAt: "2026-09-05T07:05:00.000Z",
    performerId: "device-spo2-2",
    deviceId: "device-spo2-2",
    status: "synced",
    version: 3,
    basedOnVersion: 2,
    approvalPolicy: "standard",
    approvals: ["device-gateway"],
    approvedAt: "2026-09-05T07:05:00.000Z",
    source: source(
      "sap-vitals",
      "SAP-VITAL-992",
      3,
      "2026-09-05T07:05:00.000Z",
    ),
  },
  {
    id: "o-bp-jonas-1",
    patientId: "p-jonas",
    encounterId: "enc-jonas-2026",
    code: "blood-pressure",
    label: "Blutdruck",
    value: 132,
    secondaryValue: 78,
    unit: "mmHg",
    effectiveAt: "2026-09-04T07:15:00.000Z",
    performerId: "u-nurse",
    deviceId: "device-bp-2",
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-04T07:15:00.000Z",
    source: source("wicare", "OBS-JONAS-19", 1, "2026-09-04T07:15:00.000Z"),
  },
  {
    id: "o-weight-eva-1",
    patientId: "p-eva",
    encounterId: "enc-eva-2026",
    code: "weight",
    label: "Gewicht",
    value: 67.8,
    secondaryValue: null,
    unit: "kg",
    effectiveAt: "2026-09-02T06:50:00.000Z",
    performerId: "u-nurse",
    deviceId: "device-scale-1",
    status: "synced",
    version: 2,
    basedOnVersion: 1,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-02T06:50:00.000Z",
    source: source("carecoach", "OBS-EVA-28", 2, "2026-09-02T06:50:00.000Z"),
  },
  {
    id: "o-pulse-aline-1",
    patientId: "p-aline",
    encounterId: "enc-aline-2026",
    code: "pulse",
    label: "Puls",
    value: 92,
    secondaryValue: null,
    unit: "/min",
    effectiveAt: "2026-09-01T09:40:00.000Z",
    performerId: "u-nurse",
    deviceId: null,
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-01T09:40:00.000Z",
    source: source("sap-vitals", "OBS-ALINE-12", 1, "2026-09-01T09:40:00.000Z"),
  },
  {
    id: "o-spo2-noah-1",
    patientId: "p-noah",
    encounterId: "enc-noah-2026",
    code: "oxygen-saturation",
    label: "Sauerstoffsättigung",
    value: 97,
    secondaryValue: null,
    unit: "%",
    effectiveAt: "2026-08-30T17:10:00.000Z",
    performerId: "device-spo2-3",
    deviceId: "device-spo2-3",
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["device-gateway"],
    approvedAt: "2026-08-30T17:10:00.000Z",
    source: source("sap-vitals", "OBS-NOAH-7", 1, "2026-08-30T17:10:00.000Z"),
  },
];

export const notes: ClinicalNote[] = [
  {
    id: "n-jonas-mobility",
    patientId: "p-jonas",
    encounterId: "enc-jonas-2026",
    transcript: null,
    structuredText:
      "Treppentraining mit Physiotherapie durchgeführt; nach sechs Stufen kurze Pause, danach sicher zurück ins Zimmer.",
    criticalEntities: [],
    authorId: "u-physio",
    status: "synced",
    version: 2,
    basedOnVersion: 1,
    approvalPolicy: "standard",
    approvals: ["u-physio"],
    approvedAt: "2026-09-04T10:20:00.000Z",
    provider: "wicare",
    source: source("wicare", "NOTE-JONAS-44", 2, "2026-09-04T10:20:00.000Z"),
  },
  {
    id: "n-samir-meal",
    patientId: "p-samir",
    encounterId: "enc-samir-2026",
    transcript: null,
    structuredText:
      "Mittagessen in freigegebener Konsistenz begleitet; langsam gegessen, kein Husten beobachtet.",
    criticalEntities: [],
    authorId: "u-nurse",
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-03T12:35:00.000Z",
    provider: "wicare",
    source: source("wicare", "NOTE-SAMIR-17", 1, "2026-09-03T12:35:00.000Z"),
  },
  {
    id: "n-paul-readmission",
    patientId: "p-paul",
    encounterId: "enc-paul-2026-b",
    transcript: null,
    structuredText:
      "Wiederaufnahme: frühere Dokumentation gehört zum abgeschlossenen Aufenthalt; neue Sturzabklärung offen.",
    criticalEntities: ["enc-paul-2026-b"],
    authorId: "u-nurse",
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-05T06:10:00.000Z",
    provider: "carecoach",
    source: source(
      "carecoach",
      "NOTE-PAUL-RE-1",
      1,
      "2026-09-05T06:10:00.000Z",
    ),
  },
];

export const communications: Communication[] = [
  {
    id: "c-dizziness-anna",
    patientId: "p-anna",
    encounterId: "enc-anna-2026",
    request: "Bitte Medikation und Orthostasewerte beurteilen.",
    reason: "Neuer Schwindel bei Mobilisation.",
    senderId: "u-nurse",
    recipientRole: "physician",
    recipientId: "u-physician",
    escalationRecipientRole: null,
    escalatedAt: null,
    priority: "elevated",
    dueAt: "2026-09-05T09:30:00.000Z",
    state: "sent",
    acknowledgedBy: null,
    answeredBy: null,
    response: null,
    resultingTaskId: null,
    source: source(
      "pflegehelfer",
      "Communication/c-dizziness-anna",
      1,
      "2026-09-05T07:25:00.000Z",
    ),
  },
];

export const intake: IntakeItem[] = [
  {
    id: "i-anna-id",
    patientId: "p-anna",
    label: "Identität und Aufenthalt",
    state: "complete",
    detail: "Zwei Identifikatoren und Encounter abgeglichen.",
    ownerRole: "administration",
    sourceLabels: ["SAP ADT", "WiCare"],
    taskId: null,
  },
  {
    id: "i-anna-med",
    patientId: "p-anna",
    label: "Medikationsabgleich",
    state: "discrepancy",
    detail:
      "Torasemid 5 mg in WiCare, 10 mg im Austrittsbericht. Keine automatische Zusammenführung.",
    ownerRole: "pharmacy",
    sourceLabels: ["WiCare 05.09. 06:45", "Austrittsbericht 04.09. 15:10"],
    taskId: "t-intake-anna-med",
  },
  {
    id: "i-luca-consent",
    patientId: "p-luca",
    label: "Einwilligungsdokument",
    state: "missing",
    detail: "Unterschriebenes Dokument fehlt.",
    ownerRole: "administration",
    sourceLabels: ["careCoach Dokumente"],
    taskId: "t-intake-luca-consent",
  },
];

export const roundActions: RoundAction[] = [];

export const providerHealth: ProviderHealth[] = (
  [
    "wicare",
    "carecoach",
    "sap-vitals",
    "device-gateway",
    "nurse-call",
  ] satisfies ProviderId[]
).map((provider) => ({
  provider,
  status: "available",
  latencyMs: provider === "nurse-call" ? 12 : 45,
  checkedAt: DEMO_NOW,
  message: "Simulator verfügbar",
}));
