import type {
  ClinicalNote,
  ClinicalTask,
  Communication,
  DemoUser,
  Handover,
  IntakeItem,
  Observation,
  Patient,
  ProviderHealth,
  ProviderId,
  RoundAction,
  SourceMeta,
} from "./types.js";
import { nursingPatientIds } from "./site-config.js";

const allClinicalPatientIds = [...nursingPatientIds, "p-mei"];

export const DEMO_NOW = "2026-09-05T08:00:00.000Z";

function source(
  provider: SourceMeta["provider"],
  externalId: string,
  version = 1,
  effectiveAt = DEMO_NOW,
): SourceMeta {
  return {
    provider,
    externalId,
    version,
    mappingVersion: "demo-r4-ch-core-6.0.0-v1",
    effectiveAt,
    recordedAt: effectiveAt,
    receivedAt: effectiveAt,
    syncedAt: effectiveAt,
  };
}

export const users: DemoUser[] = [
  {
    id: "u-assistant",
    displayName: "Lea Bernasconi",
    role: "care-assistant",
    wardIds: ["rehab-2"],
    patientIds: nursingPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-nurse",
    displayName: "Nora Frei",
    role: "registered-nurse",
    wardIds: ["rehab-2"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-nurse-evening",
    displayName: "Samira Vogel",
    role: "registered-nurse",
    wardIds: ["rehab-2"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-physician",
    displayName: "Dr. David Keller",
    role: "physician",
    wardIds: ["rehab-2", "ltc-1"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-physician-evening",
    displayName: "Dr. Elif Aydin",
    role: "physician",
    wardIds: ["rehab-2"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-pharmacy",
    displayName: "Giulia Rossi",
    role: "pharmacy",
    wardIds: ["rehab-2"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-physio",
    displayName: "Marc Dubois",
    role: "physiotherapy",
    wardIds: ["rehab-2"],
    patientIds: nursingPatientIds,
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-ergo",
    displayName: "Sofia Meier",
    role: "occupational-therapy",
    wardIds: ["rehab-2"],
    patientIds: ["p-mei"],
    managedDevice: true,
    defaultPurpose: "direct-care",
  },
  {
    id: "u-transport",
    displayName: "Jonas Roth",
    role: "transport",
    wardIds: ["rehab-2"],
    patientIds: ["p-luca"],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-service",
    displayName: "Elena Huber",
    role: "service",
    wardIds: ["rehab-2"],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-admin",
    displayName: "Mia Schmid",
    role: "administration",
    wardIds: ["rehab-2"],
    patientIds: allClinicalPatientIds,
    managedDevice: true,
    defaultPurpose: "administration",
  },
  {
    id: "u-manager",
    displayName: "Noah Graf",
    role: "management",
    wardIds: ["rehab-2"],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-hr",
    displayName: "Lina Wenger",
    role: "hr",
    wardIds: [],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-it",
    displayName: "Tim Gerber",
    role: "it",
    wardIds: [],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "operations",
  },
  {
    id: "u-quality",
    displayName: "Sara Baumann",
    role: "quality-safety",
    wardIds: ["rehab-2"],
    patientIds: [],
    managedDevice: true,
    defaultPurpose: "quality-review",
  },
];

export const patients: Patient[] = [
  {
    id: "p-anna",
    displayName: "Anna Beispiel",
    birthDate: "1941-03-18",
    mrn: "SH-260901-001",
    room: "214A",
    wardId: "rehab-2",
    encounterId: "enc-anna-2026",
    allergies: ["Penicillin – Exanthem"],
    risks: ["Sturzrisiko", "Antikoagulation"],
    diagnoses: [
      "Schenkelhalsfraktur links, postoperativ",
      "Arterielle Hypertonie",
    ],
    careGoals: [
      "Sicherer Transfer mit Rollator",
      "30 m Mobilisation bis 09.09.2026",
    ],
    medicationSummary: [
      "Torasemid: Diskrepanz 5 mg / 10 mg – keine Änderung in Pflegehelfer",
      "Apixaban 5 mg – nur lesbar",
    ],
    source: source("wicare", "WCD-L-10021", 7, "2026-09-05T06:45:00.000Z"),
  },
  {
    id: "p-luca",
    displayName: "Luca Demo",
    birthDate: "1937-11-02",
    mrn: "SH-260902-004",
    room: "207",
    wardId: "rehab-2",
    encounterId: "enc-luca-2026",
    allergies: [],
    risks: ["Delirrisiko", "Hörminderung"],
    diagnoses: ["Dekonditionierung nach Pneumonie"],
    careGoals: ["Selbstständige Körperpflege am Lavabo"],
    medicationSummary: ["Medikationsabgleich durch Apotheke ausstehend"],
    source: source("carecoach", "CC-88004", 4, "2026-09-05T06:30:00.000Z"),
  },
  {
    id: "p-mei",
    displayName: "Mei Muster",
    birthDate: "1948-06-27",
    mrn: "SH-260903-002",
    room: "211",
    wardId: "rehab-2",
    encounterId: "enc-mei-2026",
    allergies: ["Latex"],
    risks: ["Aspirationsrisiko"],
    diagnoses: ["Zustand nach ischämischem Insult"],
    careGoals: ["Sicheres Schlucken gemäss Logopädieplan"],
    medicationSummary: ["Medikation im KIS – schreibgeschützt"],
    source: source("sap-vitals", "SAP-PAT-7731", 3, "2026-09-05T07:00:00.000Z"),
  },
  {
    id: "p-ruth",
    displayName: "Ruth Fiktiv",
    birthDate: "1939-05-12",
    mrn: "SH-260904-006",
    room: "205",
    wardId: "rehab-2",
    encounterId: "enc-ruth-2026",
    allergies: [],
    risks: ["Sturzrisiko", "Schmerz bei Belastung"],
    diagnoses: ["Knie-Totalprothese rechts, postoperativ"],
    careGoals: ["Selbstständig ankleiden", "Sicher 20 m am Rollator"],
    medicationSummary: ["Medikation im führenden KIS – nur lesbar"],
    source: source("carecoach", "CC-88017", 2, "2026-09-05T06:35:00.000Z"),
  },
  {
    id: "p-peter",
    displayName: "Peter Beispiel",
    birthDate: "1943-09-21",
    mrn: "SH-260905-003",
    room: "208",
    wardId: "rehab-2",
    encounterId: "enc-peter-2026",
    allergies: ["Pflasterkleber"],
    risks: ["Flüssigkeitsretention", "Hautrisiko Unterschenkel"],
    diagnoses: ["Herzinsuffizienz, rehabilitative Stabilisierung"],
    careGoals: ["Gewicht täglich vergleichbar erfassen", "Ödeme beobachten"],
    medicationSummary: ["Diuretika-Verordnung im KIS – keine Änderung hier"],
    source: source("wicare", "WCD-L-10044", 5, "2026-09-05T06:42:00.000Z"),
  },
  {
    id: "p-sofia",
    displayName: "Sofia Muster",
    birthDate: "1951-01-30",
    mrn: "SH-260906-008",
    room: "216B",
    wardId: "rehab-2",
    encounterId: "enc-sofia-2026",
    allergies: [],
    risks: ["Transfer mit zwei Mitarbeitenden", "Dekubitusrisiko"],
    diagnoses: ["Hemiparese links nach Insult"],
    careGoals: ["Sicherer Transfer in den Rollstuhl", "Haut bleibt intakt"],
    medicationSummary: ["Medikation im KIS – schreibgeschützt"],
    source: source("sap-vitals", "SAP-PAT-7810", 2, "2026-09-05T06:50:00.000Z"),
  },
  {
    id: "p-emil",
    displayName: "Emil Demo",
    birthDate: "1936-07-08",
    mrn: "SH-260907-005",
    room: "203",
    wardId: "rehab-2",
    encounterId: "enc-emil-2026",
    allergies: ["Keine bekannten Allergien"],
    risks: ["Hörminderung", "Orientierung in neuer Umgebung"],
    diagnoses: ["Dekonditionierung nach abdominalem Eingriff"],
    careGoals: ["Hörhilfe selbst einsetzen", "Begleiteter Spaziergang"],
    medicationSummary: ["Medikationsabgleich abgeschlossen – nur lesbar"],
    source: source("carecoach", "CC-88029", 3, "2026-09-05T06:55:00.000Z"),
  },
];

export const tasks: ClinicalTask[] = [
  {
    id: "t-bp-anna",
    patientId: "p-anna",
    title: "Blutdruck kontrollieren",
    reason: "Erhöhter Morgenwert 168/96 mmHg",
    requesterId: "u-nurse",
    ownerRole: "care-assistant",
    ownerId: null,
    priority: "elevated",
    dueAt: "2026-09-05T08:45:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: [],
    completionEvidence: null,
    escalation: "Nach 30 Minuten an Pflegefachperson",
    source: source("pflegehelfer", "Task/t-bp-anna"),
  },
  {
    id: "t-mobilise-luca",
    patientId: "p-luca",
    title: "Mobilisation mit Rollator",
    reason: "Rehabilitationsziel",
    requesterId: "u-physio",
    ownerRole: "care-assistant",
    ownerId: "u-assistant",
    priority: "routine",
    dueAt: "2026-09-05T10:30:00.000Z",
    state: "accepted",
    acknowledgementRequired: false,
    acknowledgedAt: "2026-09-05T07:42:00.000Z",
    dependencies: [],
    comments: ["Bei Schwindel pausieren und Pflegefachperson informieren."],
    completionEvidence: null,
    escalation: "Bei Nichtdurchführung Grund dokumentieren",
    source: source("pflegehelfer", "Task/t-mobilise-luca"),
  },
  {
    id: "t-transport-luca",
    patientId: "p-luca",
    title: "Transport zur Radiologie",
    reason: "Kontrollaufnahme",
    requesterId: "u-physician",
    ownerRole: "transport",
    ownerId: null,
    priority: "routine",
    dueAt: "2026-09-05T11:20:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: [],
    completionEvidence: null,
    escalation: "Transportkoordination informieren",
    source: source("pflegehelfer", "Task/t-transport-luca"),
  },
  {
    id: "t-service-214",
    patientId: null,
    title: "Defekte Leselampe Zimmer 214",
    reason: "Patientenkomfort",
    requesterId: "u-assistant",
    ownerRole: "service",
    ownerId: null,
    priority: "routine",
    dueAt: "2026-09-05T14:00:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: ["Kein klinischer Kontext erforderlich."],
    completionEvidence: null,
    escalation: "Facility-Leitung",
    source: source("pflegehelfer", "Task/t-service-214"),
  },
  {
    id: "t-intake-anna-med",
    patientId: "p-anna",
    title: "Eintritt: Medikationsdiskrepanz klären",
    reason: "Import aus WiCare und Austrittsbericht ist widersprüchlich",
    requesterId: "system-import",
    ownerRole: "pharmacy",
    ownerId: null,
    priority: "elevated",
    dueAt: "2026-09-05T10:00:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: ["Keine Medikamentenänderung in Pflegehelfer."],
    completionEvidence: null,
    escalation: "Bei Unklarheit an ärztlichen Dienst und Pflegefachperson",
    source: source("pflegehelfer", "Task/t-intake-anna-med"),
  },
  {
    id: "t-intake-luca-consent",
    patientId: "p-luca",
    title: "Eintritt: Einwilligungsdokument nachfordern",
    reason: "Import meldet fehlendes unterschriebenes Dokument",
    requesterId: "system-import",
    ownerRole: "administration",
    ownerId: null,
    priority: "routine",
    dueAt: "2026-09-05T14:00:00.000Z",
    state: "new",
    acknowledgementRequired: true,
    acknowledgedAt: null,
    dependencies: [],
    comments: [],
    completionEvidence: null,
    escalation: "Stationsadministration informieren",
    source: source("pflegehelfer", "Task/t-intake-luca-consent"),
  },
];

export const observations: Observation[] = [
  {
    id: "o-bp-anna-1",
    patientId: "p-anna",
    code: "blood-pressure",
    label: "Blutdruck",
    value: 168,
    secondaryValue: 96,
    unit: "mmHg",
    effectiveAt: "2026-09-05T06:55:00.000Z",
    performerId: "device-bp-4",
    deviceId: "device-bp-4",
    status: "synced",
    version: 2,
    basedOnVersion: 1,
    approvalPolicy: "standard",
    approvals: ["device-gateway"],
    approvedAt: "2026-09-05T06:55:00.000Z",
    source: source(
      "device-gateway",
      "OBS-20260905-331",
      2,
      "2026-09-05T06:55:00.000Z",
    ),
  },
  {
    id: "o-temp-luca-1",
    patientId: "p-luca",
    code: "temperature",
    label: "Temperatur",
    value: 37.4,
    secondaryValue: null,
    unit: "°C",
    effectiveAt: "2026-09-05T06:40:00.000Z",
    performerId: "u-nurse",
    deviceId: null,
    status: "synced",
    version: 1,
    basedOnVersion: 0,
    approvalPolicy: "standard",
    approvals: ["u-nurse"],
    approvedAt: "2026-09-05T06:40:00.000Z",
    source: source("carecoach", "CC-VITAL-411", 1, "2026-09-05T06:40:00.000Z"),
  },
  {
    id: "o-spo2-mei-1",
    patientId: "p-mei",
    code: "oxygen-saturation",
    label: "Sauerstoffsättigung",
    value: 94,
    secondaryValue: null,
    unit: "%",
    effectiveAt: "2026-09-05T07:05:00.000Z",
    performerId: "device-spo2-2",
    deviceId: "device-spo2-2",
    status: "synced",
    version: 3,
    basedOnVersion: 2,
    approvalPolicy: "standard",
    approvals: ["device-gateway"],
    approvedAt: "2026-09-05T07:05:00.000Z",
    source: source(
      "sap-vitals",
      "SAP-VITAL-992",
      3,
      "2026-09-05T07:05:00.000Z",
    ),
  },
];

export const notes: ClinicalNote[] = [];

export const communications: Communication[] = [
  {
    id: "c-dizziness-anna",
    patientId: "p-anna",
    request: "Bitte Medikation und Orthostasewerte beurteilen.",
    reason: "Neuer Schwindel bei Mobilisation.",
    senderId: "u-nurse",
    recipientRole: "physician",
    recipientId: "u-physician",
    escalationRecipientRole: null,
    escalatedAt: null,
    priority: "elevated",
    dueAt: "2026-09-05T09:30:00.000Z",
    state: "sent",
    acknowledgedBy: null,
    answeredBy: null,
    response: null,
    resultingTaskId: null,
    source: source(
      "pflegehelfer",
      "Communication/c-dizziness-anna",
      1,
      "2026-09-05T07:25:00.000Z",
    ),
  },
];

export const intake: IntakeItem[] = [
  {
    id: "i-anna-id",
    patientId: "p-anna",
    label: "Identität und Aufenthalt",
    state: "complete",
    detail: "Zwei Identifikatoren und Encounter abgeglichen.",
    ownerRole: "administration",
    sourceLabels: ["SAP ADT", "WiCare"],
    taskId: null,
  },
  {
    id: "i-anna-med",
    patientId: "p-anna",
    label: "Medikationsabgleich",
    state: "discrepancy",
    detail:
      "Torasemid 5 mg in WiCare, 10 mg im Austrittsbericht. Keine automatische Zusammenführung.",
    ownerRole: "pharmacy",
    sourceLabels: ["WiCare 05.09. 06:45", "Austrittsbericht 04.09. 15:10"],
    taskId: "t-intake-anna-med",
  },
  {
    id: "i-luca-consent",
    patientId: "p-luca",
    label: "Einwilligungsdokument",
    state: "missing",
    detail: "Unterschriebenes Dokument fehlt.",
    ownerRole: "administration",
    sourceLabels: ["careCoach Dokumente"],
    taskId: "t-intake-luca-consent",
  },
];

export const handovers: Handover[] = [
  {
    id: "h-rehab2-morning",
    wardId: "rehab-2",
    fromShift: "Nacht",
    toShift: "Früh",
    patientIds: allClinicalPatientIds,
    deltaTaskIds: ["t-bp-anna", "t-mobilise-luca"],
    deltaObservationIds: ["o-bp-anna-1", "o-temp-luca-1", "o-spo2-mei-1"],
    unresolvedCommunicationIds: ["c-dizziness-anna"],
    narrative:
      "Teamübergabe: Anna – Blutdruck und offene Arztfrage; Luca – Mobilisation und Radiologie; Ruth – Belastungsschmerz beobachten; Peter – Gewicht und Ödeme; Sofia – Transfer zu zweit und Haut; Emil – Hörhilfe und Angehörigengespräch. Mei bleibt bei der diplomierten Pflege.",
    signedBy: "u-nurse",
    acknowledgedBy: null,
    status: "signed",
    createdAt: "2026-09-05T06:58:00.000Z",
  },
  {
    id: "h-rehab2-afternoon",
    wardId: "rehab-2",
    fromShift: "Früh",
    toShift: "Spät",
    patientIds: nursingPatientIds,
    deltaTaskIds: ["t-bp-anna", "t-mobilise-luca"],
    deltaObservationIds: ["o-bp-anna-1"],
    unresolvedCommunicationIds: ["c-dizziness-anna"],
    narrative:
      "Entwurf für die nächste Schicht: offene Ergebnisse, Teilaufgaben und Abweichungen der sechs zugewiesenen Personen einzeln bestätigen.",
    signedBy: null,
    acknowledgedBy: null,
    status: "draft",
    createdAt: "2026-09-05T12:30:00.000Z",
  },
];

export const roundActions: RoundAction[] = [];

export const providerHealth: ProviderHealth[] = (
  [
    "wicare",
    "carecoach",
    "sap-vitals",
    "device-gateway",
    "nurse-call",
  ] satisfies ProviderId[]
).map((provider) => ({
  provider,
  status: "available",
  latencyMs: provider === "nurse-call" ? 12 : 45,
  checkedAt: DEMO_NOW,
  message: "Simulator verfügbar",
}));
